---
title: "Task 2: Cake Ingredients - analysis"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r}
library(tidyverse)
library(here) 
```

```{r}
cake <- read_csv(here("clean_data/cake_clean.csv"))
```
<br>

#Insights#

<br>

### Which cake has the most cocoa in it? ###

```{r}
cake %>%
  filter(ingredient == "Cocoa") %>%
  arrange(desc(amount)) %>% 
  head(1)
```

<br>

### How many cups of ingredients are used in total in the sponge cake? ###

```{r}
cake %>%
  filter(cake == "Sponge") %>%
  filter(measure == "cup") %>%
  summarise(total_cups = sum(amount))
```

<br>

### How many ingredients are measured in teaspoons? ###

```{r}
cake %>%
  filter(measure == "teaspoon") %>%
  summarise(teaspoon_ingreds = n_distinct(ingredient))
```


### Which cake has the most unique ingredients? ###

```{r}
cake %>%
  group_by(cake) %>%
  summarise(n_ingredients = n()) %>%
  arrange(desc(n_ingredients))
```
<br>
*Babas au Rhum and One Bowl Chocolate are equal top.*

<br>

### Which ingredients are used only once? ###

```{r}
cake %>%
  group_by(ingredient) %>%
  summarise(n_cakes = n()) %>% 
  filter(n_cakes == 1)
```

