---
title: "task1_analysis"
author: "Nick Cunnington"
date: "20/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(here)
here::here()
decathalon <- read_csv(here("clean_data/decathlon_clean.csv"))
```
<br>

# Insights #

### Who had the longest long jump seen in the data? ###

```{r}
decathalon %>%
  filter(event == "long_jump") %>%
  arrange(desc(score)) %>%
  head(1)
```

<br>

### What was the average 100m time in each competition? ###

```{r}
decathalon %>%
  filter(event == "running_100m") %>%
  group_by(competition) %>%
  summarise(av_time = mean(score))
```

<br>

### Who had the highest total points across both competitions? ###

```{r}
decathalon %>%
  distinct(surname, competition, points) %>%
  group_by(surname) %>%
  summarise(points_total = sum(points)) %>%
  arrange(desc(points_total)) %>%
  head(1)
  
```
<br>

### What was the shot-put scores for the top three competitors in each competition? ###


```{r}
decathalon %>%
  filter(rank <= 3) %>%
  filter(event == "shot_put")
```

<br>

### What was the average points for competitors who ran the 400m in less than 50 seconds vs those that ran the 400m in more than 50 seconds? ###


```{r}
x400m_under50 <- clean_data %>%
  select(names, x400m, points) %>%
  filter(x400m < 50) %>%
  summarise(average_poins = mean(points))
round(x400m_under50)

```

